version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
